# Generated by Django 4.1.7 on 2023-03-02 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_following_userrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelationship',
            name='user',
        ),
        migrations.AddField(
            model_name='userrelationship',
            name='followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_relationship_as_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
