# Generated by Django 4.1.7 on 2023-04-08 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_userrelationship_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='replies',
            field=models.ManyToManyField(blank=True, to='base.message'),
        ),
    ]
