# Generated by Django 4.1.7 on 2023-04-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message_height_message_likes_message_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='height',
        ),
    ]
