# Generated by Django 4.1.7 on 2023-04-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
